[package]
name = "AftermathAmm"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "74e8414a4"

[dependencies.ProtocolFeeVault]
local = "../amm-protocol-fee-vault/"

[dependencies.AmmMath]
local = "../amm-math/"

[addresses]
amm = "0xefe170ec0be4d762196bedecd7a065816576198a6527c99282a2551aaa7da38c"